import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar/page.jsx";
import Footer from "./footer/page.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <Navbar/>
        <main className="relative overflow-hidden">
         {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
